import type {Metadata, Viewport} from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/pagination';

const golosText = Golos_Text({
  variable: "--font-golos-text",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: 'rgb(115 95 250)',
    colorScheme: 'light',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${golosText.variable}`}
      >
        <div id='top' />
        {children}
      </body>
    </html>
  );
}
